[package]
name = "helpers"
version = "0.1.0"
edition = "2021"
default_run = "helpers"

[[bin]]
name = "create-docx"
path = "helpers/main.rs"

[dependencies]
anyhow = "1.0.94"
docx-rs = "0.4.17"
serde = "1.0.215"
serde_json = "1.0.133"
toml = "0.8.19"
