name: Continous Integration

on:
  push:
  pull_request:

env:
  ZIG_VERSION: 0.13.0
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.os }}-${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux builds
          - os: ubuntu-latest
            arch: x64
            target: x86_64-unknown-linux-gnu
            zig-target: x86_64-linux-gnu
          - os: ubuntu-latest
            arch: arm64
            target: aarch64-unknown-linux-gnu
            zig-target: aarch64-linux-gnu
          # Windows builds
          - os: windows-latest
            arch: x64
            target: x86_64-pc-windows-msvc
            zig-target: x86_64-windows-msvc
          - os: windows-latest
            arch: arm64
            target: aarch64-pc-windows-msvc
            zig-target: aarch64-windows-msvc
          # macOS builds
          - os: macos-latest
            arch: arm64
            target: aarch64-apple-darwin
            zig-target: aarch64-macos-none

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        
      - name: Zig Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/zig
            zig-cache
          key: zig-${{ matrix.os }}-${{ matrix.arch }}-${{ env.ZIG_VERSION }}

      - name: Build Zig Project
        run: zig build -Doptimize=ReleaseSafe -Dtarget=${{ matrix.zig-target }} -freference-trace

      - name: Build Rust Project
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true